# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Device(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, dev_id: int=None, device_name: str=None):  # noqa: E501
        """Device - a model defined in Swagger

        :param dev_id: The dev_id of this Device.  # noqa: E501
        :type dev_id: int
        :param device_name: The device_name of this Device.  # noqa: E501
        :type device_name: str
        """
        self.swagger_types = {
            'dev_id': int,
            'device_name': str
        }

        self.attribute_map = {
            'dev_id': 'dev_id',
            'device_name': 'device_name'
        }

        self._dev_id = dev_id
        self._device_name = device_name

    @classmethod
    def from_dict(cls, dikt) -> 'Device':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The device of this Device.  # noqa: E501
        :rtype: Device
        """
        return util.deserialize_model(dikt, cls)

    @property
    def dev_id(self) -> int:
        """Gets the dev_id of this Device.


        :return: The dev_id of this Device.
        :rtype: int
        """
        return self._dev_id

    @dev_id.setter
    def dev_id(self, dev_id: int):
        """Sets the dev_id of this Device.


        :param dev_id: The dev_id of this Device.
        :type dev_id: int
        """

        self._dev_id = dev_id

    @property
    def device_name(self) -> str:
        """Gets the device_name of this Device.


        :return: The device_name of this Device.
        :rtype: str
        """
        return self._device_name

    @device_name.setter
    def device_name(self, device_name: str):
        """Sets the device_name of this Device.


        :param device_name: The device_name of this Device.
        :type device_name: str
        """

        self._device_name = device_name
